# Generated by Django 4.2.7 on 2024-11-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('mat_exp', models.FloatField()),
                ('sigm', models.FloatField()),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'CategoryMetric',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('column', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'report',
            },
        ),
    ]
