# Generated by Django 4.2.7 on 2024-11-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_yandexoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yandexoffer',
            name='article',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='yandexoffer',
            name='available',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='yandexoffer',
            name='barcode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='yandexoffer',
            name='categoryId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='yandexoffer',
            name='currencyId',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='yandexoffer',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='yandexoffer',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='yandexoffer',
            name='newby',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='yandexoffer',
            name='picture',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='yandexoffer',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='yandexoffer',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='yandexoffer',
            name='review_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='yandexoffer',
            name='sale',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='yandexoffer',
            name='vendor',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
