# Generated by Django 4.2.7 on 2024-11-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_yandexoffer_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='advice',
            field=models.CharField(default='', max_length=200),
        ),
    ]
