# Generated by Django 4.2.7 on 2024-11-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_yandexoffer_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='index',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='yandexoffer',
            name='barcode',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='yandexoffer',
            name='categoryId',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='yandexoffer',
            name='index',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='yandexoffer',
            name='review_amount',
            field=models.BigIntegerField(null=True),
        ),
    ]
