# Generated by Django 4.2.7 on 2024-11-29 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_category_name_alter_report_column_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('index', 'column')},
        ),
    ]
