# Generated by Django 4.2.7 on 2024-11-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_report_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yandexoffer',
            name='barcode',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
