# Generated by Django 4.2.7 on 2024-11-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_yandexoffer_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yandexoffer',
            name='description',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
