# Generated by Django 4.2.7 on 2024-11-29 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_report_column_alter_report_index'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='categorymetric',
        ),
    ]
